// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xtpuoxootggtrzransrz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh0cHVveG9vdGdndHJ6cmFuc3J6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE1NzUzMjYsImV4cCI6MjA4NzE1MTMyNn0.Tmma4kRnrgVVD7EXSq8SEOPwNzTZjO7qHU-FuMAeG9c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});